[build]
  publish = "dist"
  command = "npm ci --prefer-offline --no-audit --no-fund && npm run build"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  CI = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
